application: malcat
version: 1
runtime: python27

handlers:
- url: /series
  static_dir: MalCat

- url: .*
  script: main.app
  
libraries:
- name: webapp2
  version: "2.5.2"
        
- name: jinja2
  version: latest
 
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 5
  max_instances: 100
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50