application: MalCat
version: 1
runtime: python27

handlers:
- url: /series
  static_dir: MalCat

-url: .*
  script: main.app
  
libraries:
- name: webapp2
  version: "2.5.2"
        
- name: jinja2
  version: latest